[2025-07-04T15:48:34.821+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: retail_etl_dag.clean_data scheduled__2025-07-03T00:00:00+00:00 [queued]>
[2025-07-04T15:48:34.828+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: retail_etl_dag.clean_data scheduled__2025-07-03T00:00:00+00:00 [queued]>
[2025-07-04T15:48:34.829+0530] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-07-04T15:48:34.844+0530] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): clean_data> on 2025-07-03 00:00:00+00:00
[2025-07-04T15:48:34.847+0530] {standard_task_runner.py:57} INFO - Started process 25034 to run task
[2025-07-04T15:48:34.855+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'retail_etl_dag', 'clean_data', 'scheduled__2025-07-03T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/retail_etl_dag.py', '--cfg-path', '/var/folders/53/tbd296vx2878lwlskxvm_8h80000gp/T/tmp88iy2d9g']
[2025-07-04T15:48:34.859+0530] {standard_task_runner.py:85} INFO - Job 25: Subtask clean_data
[2025-07-04T15:48:34.917+0530] {task_command.py:416} INFO - Running <TaskInstance: retail_etl_dag.clean_data scheduled__2025-07-03T00:00:00+00:00 [running]> on host v-macbook-pro.local
[2025-07-04T15:48:34.979+0530] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='retail_etl_dag' AIRFLOW_CTX_TASK_ID='clean_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-03T00:00:00+00:00'
[2025-07-04T15:48:34.982+0530] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/53/tbd296vx2878lwlskxvm_8h80000gp/T
[2025-07-04T15:48:34.983+0530] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'spark-submit /Users/vaish/databorn_etl_project/retail_etl/etl_pipeline_project/spark_jobs/clean_data.py --input "/Users/vaish/databorn_etl_project/retail_etl/etl_pipeline_project/data/raw/OnlineRetail.csv" --output "/Users/vaish/databorn_etl_project/retail_etl/etl_pipeline_project/data/processed/cleaned_data.csv"']
[2025-07-04T15:48:34.991+0530] {subprocess.py:86} INFO - Output:
[2025-07-04T15:48:35.720+0530] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-04T15:48:35.726+0530] {subprocess.py:93} INFO -   File "/Users/vaish/databorn_etl_project/retail_etl/etl_pipeline_project/venv/bin/find_spark_home.py", line 95, in <module>
[2025-07-04T15:48:35.727+0530] {subprocess.py:93} INFO -     print(_find_spark_home())
[2025-07-04T15:48:35.727+0530] {subprocess.py:93} INFO -           ~~~~~~~~~~~~~~~~^^
[2025-07-04T15:48:35.728+0530] {subprocess.py:93} INFO -   File "/Users/vaish/databorn_etl_project/retail_etl/etl_pipeline_project/venv/bin/find_spark_home.py", line 59, in _find_spark_home
[2025-07-04T15:48:35.728+0530] {subprocess.py:93} INFO -     module_home = os.path.dirname(find_spec("pyspark").origin)
[2025-07-04T15:48:35.729+0530] {subprocess.py:93} INFO -                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-04T15:48:35.729+0530] {subprocess.py:93} INFO - AttributeError: 'NoneType' object has no attribute 'origin'
[2025-07-04T15:48:35.735+0530] {subprocess.py:93} INFO - /Users/vaish/databorn_etl_project/retail_etl/etl_pipeline_project/venv/bin/spark-submit: line 27: /bin/spark-class: No such file or directory
[2025-07-04T15:48:35.736+0530] {subprocess.py:93} INFO - /Users/vaish/databorn_etl_project/retail_etl/etl_pipeline_project/venv/bin/spark-submit: line 27: exec: /bin/spark-class: cannot execute: No such file or directory
[2025-07-04T15:48:35.736+0530] {subprocess.py:97} INFO - Command exited with return code 126
[2025-07-04T15:48:35.744+0530] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/vaish/databorn_etl_project/retail_etl/etl_pipeline_project/venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 126.
[2025-07-04T15:48:35.750+0530] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=retail_etl_dag, task_id=clean_data, execution_date=20250703T000000, start_date=20250704T101834, end_date=20250704T101835
[2025-07-04T15:48:35.761+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 25 for task clean_data (Bash command failed. The command returned a non-zero exit code 126.; 25034)
[2025-07-04T15:48:35.801+0530] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-07-04T15:48:35.823+0530] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-04T16:04:51.752+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: retail_etl_dag.clean_data scheduled__2025-07-03T00:00:00+00:00 [queued]>
[2025-07-04T16:04:51.759+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: retail_etl_dag.clean_data scheduled__2025-07-03T00:00:00+00:00 [queued]>
[2025-07-04T16:04:51.759+0530] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-07-04T16:04:51.774+0530] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): clean_data> on 2025-07-03 00:00:00+00:00
[2025-07-04T16:04:51.777+0530] {standard_task_runner.py:57} INFO - Started process 31376 to run task
[2025-07-04T16:04:51.785+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'retail_etl_dag', 'clean_data', 'scheduled__2025-07-03T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/retail_etl_dag.py', '--cfg-path', '/var/folders/53/tbd296vx2878lwlskxvm_8h80000gp/T/tmpwr6klctq']
[2025-07-04T16:04:51.789+0530] {standard_task_runner.py:85} INFO - Job 36: Subtask clean_data
[2025-07-04T16:04:51.846+0530] {task_command.py:416} INFO - Running <TaskInstance: retail_etl_dag.clean_data scheduled__2025-07-03T00:00:00+00:00 [running]> on host v-macbook-pro.local
[2025-07-04T16:04:51.912+0530] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='retail_etl_dag' AIRFLOW_CTX_TASK_ID='clean_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-03T00:00:00+00:00'
[2025-07-04T16:04:51.916+0530] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/53/tbd296vx2878lwlskxvm_8h80000gp/T
[2025-07-04T16:04:51.917+0530] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'spark-submit /Users/vaish/databorn_etl_project/retail_etl/etl_pipeline_project/spark_jobs/clean_data.py --input "/Users/vaish/databorn_etl_project/retail_etl/etl_pipeline_project/data/raw/OnlineRetail.csv" --output "/Users/vaish/databorn_etl_project/retail_etl/etl_pipeline_project/data/processed/cleaned_data.csv"']
[2025-07-04T16:04:51.928+0530] {subprocess.py:86} INFO - Output:
[2025-07-04T16:04:52.192+0530] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-04T16:04:52.230+0530] {subprocess.py:93} INFO -   File "/Users/vaish/databorn_etl_project/retail_etl/etl_pipeline_project/venv/bin/find_spark_home.py", line 95, in <module>
[2025-07-04T16:04:52.231+0530] {subprocess.py:93} INFO -     print(_find_spark_home())
[2025-07-04T16:04:52.231+0530] {subprocess.py:93} INFO -           ~~~~~~~~~~~~~~~~^^
[2025-07-04T16:04:52.232+0530] {subprocess.py:93} INFO -   File "/Users/vaish/databorn_etl_project/retail_etl/etl_pipeline_project/venv/bin/find_spark_home.py", line 59, in _find_spark_home
[2025-07-04T16:04:52.234+0530] {subprocess.py:93} INFO -     module_home = os.path.dirname(find_spec("pyspark").origin)
[2025-07-04T16:04:52.235+0530] {subprocess.py:93} INFO -                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-04T16:04:52.235+0530] {subprocess.py:93} INFO - AttributeError: 'NoneType' object has no attribute 'origin'
[2025-07-04T16:04:52.253+0530] {subprocess.py:93} INFO - /Users/vaish/databorn_etl_project/retail_etl/etl_pipeline_project/venv/bin/spark-submit: line 27: /bin/spark-class: No such file or directory
[2025-07-04T16:04:52.254+0530] {subprocess.py:93} INFO - /Users/vaish/databorn_etl_project/retail_etl/etl_pipeline_project/venv/bin/spark-submit: line 27: exec: /bin/spark-class: cannot execute: No such file or directory
[2025-07-04T16:04:52.256+0530] {subprocess.py:97} INFO - Command exited with return code 126
[2025-07-04T16:04:52.274+0530] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/vaish/databorn_etl_project/retail_etl/etl_pipeline_project/venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 126.
[2025-07-04T16:04:52.284+0530] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=retail_etl_dag, task_id=clean_data, execution_date=20250703T000000, start_date=20250704T103451, end_date=20250704T103452
[2025-07-04T16:04:52.309+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 36 for task clean_data (Bash command failed. The command returned a non-zero exit code 126.; 31376)
[2025-07-04T16:04:52.320+0530] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-07-04T16:04:52.347+0530] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-04T16:12:23.142+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: retail_etl_dag.clean_data scheduled__2025-07-03T00:00:00+00:00 [queued]>
[2025-07-04T16:12:23.151+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: retail_etl_dag.clean_data scheduled__2025-07-03T00:00:00+00:00 [queued]>
[2025-07-04T16:12:23.151+0530] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-07-04T16:12:23.165+0530] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): clean_data> on 2025-07-03 00:00:00+00:00
[2025-07-04T16:12:23.168+0530] {standard_task_runner.py:57} INFO - Started process 33150 to run task
[2025-07-04T16:12:23.177+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'retail_etl_dag', 'clean_data', 'scheduled__2025-07-03T00:00:00+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/retail_etl_dag.py', '--cfg-path', '/var/folders/53/tbd296vx2878lwlskxvm_8h80000gp/T/tmpf8mhsn1r']
[2025-07-04T16:12:23.182+0530] {standard_task_runner.py:85} INFO - Job 44: Subtask clean_data
[2025-07-04T16:12:23.243+0530] {task_command.py:416} INFO - Running <TaskInstance: retail_etl_dag.clean_data scheduled__2025-07-03T00:00:00+00:00 [running]> on host v-macbook-pro.local
[2025-07-04T16:12:23.320+0530] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='retail_etl_dag' AIRFLOW_CTX_TASK_ID='clean_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-03T00:00:00+00:00'
[2025-07-04T16:12:23.324+0530] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/53/tbd296vx2878lwlskxvm_8h80000gp/T
[2025-07-04T16:12:23.325+0530] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'spark-submit /Users/vaish/databorn_etl_project/retail_etl/etl_pipeline_project/spark_jobs/clean_data.py --input "/Users/vaish/databorn_etl_project/retail_etl/etl_pipeline_project/data/raw/OnlineRetail.csv" --output "/Users/vaish/databorn_etl_project/retail_etl/etl_pipeline_project/data/processed/cleaned_data.csv"']
[2025-07-04T16:12:23.333+0530] {subprocess.py:86} INFO - Output:
[2025-07-04T16:12:23.604+0530] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-04T16:12:23.614+0530] {subprocess.py:93} INFO -   File "/Users/vaish/databorn_etl_project/retail_etl/etl_pipeline_project/venv/bin/find_spark_home.py", line 95, in <module>
[2025-07-04T16:12:23.615+0530] {subprocess.py:93} INFO -     print(_find_spark_home())
[2025-07-04T16:12:23.616+0530] {subprocess.py:93} INFO -           ~~~~~~~~~~~~~~~~^^
[2025-07-04T16:12:23.616+0530] {subprocess.py:93} INFO -   File "/Users/vaish/databorn_etl_project/retail_etl/etl_pipeline_project/venv/bin/find_spark_home.py", line 59, in _find_spark_home
[2025-07-04T16:12:23.617+0530] {subprocess.py:93} INFO -     module_home = os.path.dirname(find_spec("pyspark").origin)
[2025-07-04T16:12:23.618+0530] {subprocess.py:93} INFO -                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-04T16:12:23.619+0530] {subprocess.py:93} INFO - AttributeError: 'NoneType' object has no attribute 'origin'
[2025-07-04T16:12:23.628+0530] {subprocess.py:93} INFO - /Users/vaish/databorn_etl_project/retail_etl/etl_pipeline_project/venv/bin/spark-submit: line 27: /bin/spark-class: No such file or directory
[2025-07-04T16:12:23.628+0530] {subprocess.py:93} INFO - /Users/vaish/databorn_etl_project/retail_etl/etl_pipeline_project/venv/bin/spark-submit: line 27: exec: /bin/spark-class: cannot execute: No such file or directory
[2025-07-04T16:12:23.629+0530] {subprocess.py:97} INFO - Command exited with return code 126
[2025-07-04T16:12:23.649+0530] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/vaish/databorn_etl_project/retail_etl/etl_pipeline_project/venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 126.
[2025-07-04T16:12:23.658+0530] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=retail_etl_dag, task_id=clean_data, execution_date=20250703T000000, start_date=20250704T104223, end_date=20250704T104223
[2025-07-04T16:12:23.680+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 44 for task clean_data (Bash command failed. The command returned a non-zero exit code 126.; 33150)
[2025-07-04T16:12:23.713+0530] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-07-04T16:12:23.758+0530] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
